### ISSUE TITLE
[Settings] Crash on starting settings module

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#139]
Here's the error:
Running FLExTrans.Settings Tool (version 1.0)...
Module failed with exception AttributeError! Use Ctrl-C to copy this report to the clipboard to see more information.
AttributeError: 
Traceback (most recent call last):
  File "C:\Data\FLExTrans\FlexTools2.0 Active Projects\FlexTools\FTModules.py", line 199, in RunModules
    modify=modifyDB)
  File "C:\Data\FLExTrans\FlexTools2.0 Active Projects\FlexTools\FTModuleClass.py", line 109, in Run
    self.runFunction(DB, report, modify)
  File "C:\Data\FLExTrans\FlexTools2.0 Active Projects\FlexTools\Modules\FLExTrans\SettingsGUI.py", line 393, in MainFunction
    window = Main(configMap, report, TargetDB, DB,) #sourceDB
  File "C:\Data\FLExTrans\FlexTools2.0 Active Projects\FlexTools\Modules\FLExTrans\SettingsGUI.py", line 73, in __init__
    self.init_load()
  File "C:\Data\FLExTrans\FlexTools2.0 Active Projects\FlexTools\Modules\FLExTrans\SettingsGUI.py", line 178, in init_load
    self.ui.chose_source_compex_types.check(string)
AttributeError: 'QComboBox' object has no attribute 'check'

**Comment by pipfugl99** [comment]
The problem is that QComboBox does not have such a method, but the checkable combo box I have made does and this is the method it is suposed to call. It seams like it has difficulties to find the correct class.

**Comment by rmlockwood** [comment]
Maybe try it in a new install folder and see if you get the same error.

**Comment by pipfugl99** [comment]
I'm not sure, I haven't had time to test it yet, I will test it tomorrow, but I hope I have fixed it

**Comment by rmlockwood** [comment]
Ok, I just got the latest code and it seems to be working.
