### ISSUE TITLE
[Rule Assistant] error on Save and Create, where a "random" rule was created

### ISSUE THREAD

**Issue by SaraMeiSL** [rmlockwood/FLExTrans#643]
The first rule in the RA was created, with no regard for the languages in question, as so: 
![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/157a57d4-0266-4d68-8fa6-1b91b22e9c93)

On use of "save and create all" the error below was seen.

Whilst I understand that the aim is to create "sensible rules", there will be times when a user gets a rule wrong. What about some kind of rule validation in the RA to catch rule errors before creation in the .t1x file?

~~~~~~~~~~
Running single module...
Opening project German-FLExTrans-Sample...

Running Rule Assistant (version 3.11)...
Using: Swedish-FLExTrans-Sample as the target database.
Copying prior version of transfer rules to C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\WorkProjects\German-Swedish\transfer_rules-Swedish.t1x.2024-05-16 12-41-55.bak.
Module failed with exception KeyError! Use Ctrl-C to copy this report to the clipboard to see more information.
KeyError: 
Traceback (most recent call last):
  File "C:\Users\stuar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 238, in RunModules
    self.__modules[moduleName].Run(self.project,
  File "C:\Users\stuar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModuleClass.py", line 110, in Run
    self.runFunction(project, report, modifyAllowed)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\WorkProjects\German-Swedish\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 275, in MainFunction
    CreateApertiumRules.CreateRules(TargetDB, report, configMap, ruleAssistantFile, tranferRulePath, rule)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 650, in CreateRules
    generator.ProcessAssistantFile(ruleAssistantFile, ruleNumber)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 609, in ProcessAssistantFile
    if self.ProcessRule(rule):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 442, in ProcessRule
    ET.SubElement(patternEl, 'pattern-item', n=self.tagToCategoryName[cat])
                                               ~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: ''

Processing completed with 1 error and 0 warnings

**Comment by SaraMeiSL** [comment]
I then deleted the two rules that I had created that "did something", leaving only three rules that are the default, and I still get a KeyError, as below (probably the same error). 

Running single module...
Opening project German-FLExTrans-Sample...

Running Rule Assistant (version 3.11)...
Using: Swedish-FLExTrans-Sample as the target database.
Copying prior version of transfer rules to C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\WorkProjects\German-Swedish\transfer_rules-Swedish.t1x.2024-05-16 12-53-33.bak.
Module failed with exception KeyError! Use Ctrl-C to copy this report to the clipboard to see more information.
KeyError: 
Traceback (most recent call last):
  File "C:\Users\stuar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 238, in RunModules
    self.__modules[moduleName].Run(self.project,
  File "C:\Users\stuar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModuleClass.py", line 110, in Run
    self.runFunction(project, report, modifyAllowed)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\WorkProjects\German-Swedish\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 275, in MainFunction
    CreateApertiumRules.CreateRules(TargetDB, report, configMap, ruleAssistantFile, tranferRulePath, rule)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 650, in CreateRules
    generator.ProcessAssistantFile(ruleAssistantFile, ruleNumber)
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 609, in ProcessAssistantFile
    if self.ProcessRule(rule):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stuar\Documents\FLExTransWithRA\FLExTrans\FlexTools\Modules\FlexTrans\Lib\CreateApertiumRules.py", line 442, in ProcessRule
    ET.SubElement(patternEl, 'pattern-item', n=self.tagToCategoryName[cat])
                                               ~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: ''

Processing completed with 1 error and 0 warnings

**Comment by SaraMeiSL** [comment]
Then I deleted all rules except one, and tried Save & Create and also Save & Create All, but still there are KeyErrors, and no .t1x file is created with the RA rule. 
Rule that is left:
![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/ef605aa8-11f5-4ea4-9389-21dc38f24b70)

**Comment by mr-martian** [comment]
That error indicates that you have a source word which is missing a category in one of your rules. I have added a check for it in #636.

**Comment by rmlockwood** [comment]
This appears to be fixed. Now you can't create a rule unless you have features defined somewhere on the target phrase. Also, you have to mark a target word as head. Once you do all these things a rule does get created or a valid error is given.
Feel free to test this further and reopen this issue, if needed.
