### ISSUE TITLE
[Rule Assistant] "number of arguments" error in reading templates

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#648]
I tried running the rule assistant with the German-Swedish sample projects.  There happen to be no templates in the Swedish project, but I don't know if that is the problem.  Instead I got this message:

(This is with FLExTrans 3.11 downloaded on 5/21/24)

Running single module...
Opening project German-FLExTrans-Sample...

Running Rule Assistant (version 3.11)...
Using: Swedish-FLExTrans-Sample as the target database.
Module failed with exception TypeError! Use Ctrl-C to copy this report to the clipboard to see more information.
TypeError: 
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 238, in RunModules
    self.__modules[moduleName].Run(self.project,
  File "C:\Program Files\Python311\Lib\site-packages\flextoolslib\code\FTModuleClass.py", line 110, in Run
    self.runFunction(project, report, modifyAllowed)
  File "C:\Users\Beth Bryson\Documents\FLExTrans\WorkProjects\German-Swedish\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 281, in MainFunction
    startData = GetRuleAssistantStartData(report, DB, TargetDB, configMap)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Beth Bryson\Documents\FLExTrans\WorkProjects\German-Swedish\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 184, in GetRuleAssistantStartData
    templates = Utils.getAffixTemplates(TargetDB, report, cat)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: getAffixTemplates() takes 2 positional arguments but 3 were given

Processing completed with 1 error and 0 warnings

**Comment by mr-martian** [comment]
This is actually unrelated to a lack of templates, I just committed a version of the code that had a typo in it.

**Comment by bbryson** [comment]
This got fixed and shipped.
