### ISSUE TITLE
[Rule Assistant] Crash when using new LRT loop feature

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#743]
I ran the RA on a certain project and got:
Traceback (most recent call last):
  File "C:\Users\rlboo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModules.py", line 238, in RunModules
    self.__modules[moduleName].Run(self.project,
  File "C:\Users\rlboo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flextoolslib\code\FTModuleClass.py", line 110, in Run
    self.runFunction(project, report, modifyAllowed)
  File "C:\Data\FLExTrans\Dev\Active Projects\WorkProjects\fa-bcc\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 384, in MainFunction
    startData = GetRuleAssistantStartData(report, DB, TargetDB, configMap)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data\FLExTrans\Dev\Active Projects\WorkProjects\fa-bcc\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 209, in GetRuleAssistantStartData
    GetStartData(report, TargetDB, configMap))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data\FLExTrans\Dev\Active Projects\WorkProjects\fa-bcc\Config\..\..\..\FlexTools\Modules\FLExTrans\RuleAssistant.py", line 191, in GetStartData
    templates = Utils.getAffixTemplates(DB, cat)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Data\FLExTrans\Dev\Active Projects\FlexTools\Modules\FlexTrans\Lib\Utils.py", line 2263, in getAffixTemplates
    cats, types = list(zip(*slots))
    ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by rmlockwood** [comment]
fixed in LRT loop branch.
